
{-
 - Problem 1
 -
 - Multiples of 3 and 5
 -
 - If we list all the natural numbers below 10 that are multiples of 3 or 5, we get
 - 3, 5, 6 and 9. The sum of these multiples is 23.
 - 
 - Find the sum of all the multiples of 3 or 5 below 1000.
-}

problem_1 = sum [x | x <- [1..999], mod x 3 == 0 || mod x 5 == 0]

{-
 - Problem 2
 -
 - Even Fibonacci numbers
 -
 - Each new term in the Fibonacci sequence is generated by adding the previous
 - two terms. By starting with 1 and 2, the first 10 terms will be:
 -              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 - By considering the terms in the Fibonacci sequence whose values do not exceed
 - four million, find the sum of the even-valued terms.
-}

fib = 1 : 1 : zipWith (+) fib (tail fib)

problem_2 = sum [x | x <- takeWhile (< 4000000) fib, even x]

{-
 - Problem 3
 -
 - Largest prime factor
 -
 - The prime factors of 13195 are 5, 7, 13 and 29.
 - 
 - What is the largest prime factor of the number 600851475143 ?
-}

lPF :: Integer -> Integer
lPF x =
    let
        z = sPF x
    in
        if x == z then z else lPF (div x z)

sPF x = head [k | k <- [2..x], mod x k == 0]

problem_3 = lPF (600851475143 :: Integer)



{-
 - Problem 4
 -
 - Largest palindrome product
 - 
 - A palindromic number reads the same both ways. The largest palindrome made from
 - the product of two 2-digit numbers is 9009 = 91 × 99.
 - 
 - Find the largest palindrome made from the product of two 3-digit numbers.
-}
